// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT11awq42WpxRsPoK2sIHAE7r2QPCT3do',
    appId: '1:489394886038:web:be2a1bd904a9902a0039b7',
    messagingSenderId: '489394886038',
    projectId: 'fcmtest-9e091',
    authDomain: 'fcmtest-9e091.firebaseapp.com',
    storageBucket: 'fcmtest-9e091.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArRKH2S02WGdVJpNz7a8_mzQjdJ-t_42A',
    appId: '1:489394886038:android:8c25e8d0f1c302000039b7',
    messagingSenderId: '489394886038',
    projectId: 'fcmtest-9e091',
    storageBucket: 'fcmtest-9e091.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoiHFgFqS4DEfSPXzoNbn7atB6V0RYOTM',
    appId: '1:489394886038:ios:ec174a74c7bede330039b7',
    messagingSenderId: '489394886038',
    projectId: 'fcmtest-9e091',
    storageBucket: 'fcmtest-9e091.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoiHFgFqS4DEfSPXzoNbn7atB6V0RYOTM',
    appId: '1:489394886038:ios:85d744be9e54bccb0039b7',
    messagingSenderId: '489394886038',
    projectId: 'fcmtest-9e091',
    storageBucket: 'fcmtest-9e091.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
